### PR TITLE
allow fuelingLoad instead of engine_load

### PR DESCRIPTION
**Pull request by mck1117**
#8 but forked off the correct branch

### CODE REVIEW

**Comment by mck1117** [comment]
probably fixes https://github.com/rusefi/web_backend/issues/126

**Comment by rusefillc** [comment]
@andreika-git what do you think?

**Comment by andreika-git** [comment]
What if both "engine_load" and "fuelingLoad" are absent?

**Comment by mck1117** [comment]
The impetus was that engine_load was removed, but fuelingLoad is always present now.

**Pull request merged**
